# Generated by Django 5.2.4 on 2025-07-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_comment'),
        ('todo', '0002_task_like'),
    ]

    operations = [
    ]
